-- Drivers Lounge RC2 first-party advertising system.
-- Driver interaction is intentionally limited to simple listen/save actions.

create table if not exists ad_campaigns (
  id uuid primary key default gen_random_uuid(),
  business_account_id uuid references business_accounts(id) on delete set null,
  advertiser_name text not null,
  title text not null,
  body text,
  image_url text,
  audio_url text,
  destination_url text not null,
  category text,
  target_states text[] default '{}',
  active boolean not null default false,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists ad_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references ad_campaigns(id) on delete cascade,
  user_id uuid,
  event_type text not null check (event_type in ('impression','audio_play','audio_complete','save','open_later')),
  created_at timestamptz default now()
);

create table if not exists saved_offers (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references ad_campaigns(id) on delete cascade,
  user_id uuid not null,
  delivery_preference text not null default 'in_app' check (delivery_preference in ('in_app','email','sms')),
  delivery_status text not null default 'saved' check (delivery_status in ('saved','queued','sent','failed')),
  created_at timestamptz default now(),
  unique(campaign_id,user_id)
);

alter table ad_campaigns enable row level security;
alter table ad_events enable row level security;
alter table saved_offers enable row level security;

drop policy if exists "active ads public read" on ad_campaigns;
create policy "active ads public read" on ad_campaigns for select using (active = true and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at >= now()));

drop policy if exists "authenticated ad events" on ad_events;
create policy "authenticated ad events" on ad_events for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "users save own offers" on saved_offers;
create policy "users save own offers" on saved_offers for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "users read own offers" on saved_offers;
create policy "users read own offers" on saved_offers for select to authenticated using (user_id = auth.uid());
drop policy if exists "users update own offers" on saved_offers;
create policy "users update own offers" on saved_offers for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

grant select on ad_campaigns to anon, authenticated;
grant insert on ad_events to authenticated;
grant select,insert,update on saved_offers to authenticated;