import Stripe from 'stripe';import {NextResponse} from 'next/server';import {createClient} from '@supabase/supabase-js';

function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase admin env vars missing');return createClient(url,key,{auth:{persistSession:false}})}

export async function POST(req:Request){const secret=process.env.STRIPE_WEBHOOK_SECRET;const stripeKey=process.env.STRIPE_SECRET_KEY;if(!secret||!stripeKey)return NextResponse.json({error:'Stripe webhook not configured'},{status:503});const stripe=new Stripe(stripeKey);const sig=req.headers.get('stripe-signature');if(!sig)return NextResponse.json({error:'Missing signature'},{status:400});const raw=await req.text();let event:Stripe.Event;try{event=stripe.webhooks.constructEvent(raw,sig,secret)}catch{return NextResponse.json({error:'Invalid signature'},{status:400})}const s=adminClient();const existing=await s.from('payment_events').select('id').eq('provider_event_id',event.id).maybeSingle();if(existing.data)return NextResponse.json({received:true,duplicate:true});

if(event.type==='checkout.session.completed'){const session=event.data.object as Stripe.Checkout.Session;const userId=session.metadata?.user_id||null;const product=session.metadata?.product||null;await s.from('payment_events').insert({provider_event_id:event.id,event_type:event.type,user_id:userId,product_code:product,amount_total:session.amount_total,currency:session.currency,status:'processed',payload:session});if(userId&&product){if(product==='single')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'load_credit',quantity:1,source_reference:session.id});if(product==='pack10')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'load_pack',quantity:10,source_reference:session.id});if(product==='unlimited')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'unlimited_posting',quantity:0,source_reference:session.id,ends_at:new Date(Date.now()+32*24*60*60*1000).toISOString()});if(product?.startsWith('ad_')&&session.metadata?.campaign_id)await s.from('advertising_campaigns').update({active:true}).eq('id',session.metadata.campaign_id)}}

if(event.type==='customer.subscription.deleted'){const sub=event.data.object as Stripe.Subscription;const userId=sub.metadata?.user_id;if(userId)await s.from('account_entitlements').update({active:false}).eq('user_id',userId).eq('entitlement_type','unlimited_posting')}
return NextResponse.json({received:true})}
