import Stripe from 'stripe';import {NextResponse} from 'next/server';import {createClient} from '@supabase/supabase-js';
function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase admin env vars missing');return createClient(url,key,{auth:{persistSession:false}})}
async function record(s:any,event:Stripe.Event,userId?:string|null,product?:string|null,amount?:number|null,currency?:string|null,payload?:any){await s.from('payment_events').insert({provider_event_id:event.id,event_type:event.type,user_id:userId||null,product_code:product||null,amount_total:amount||null,currency:currency||null,status:'processed',payload})}
export async function POST(req:Request){const secret=process.env.STRIPE_WEBHOOK_SECRET;const stripeKey=process.env.STRIPE_SECRET_KEY;if(!secret||!stripeKey)return NextResponse.json({error:'Stripe webhook not configured'},{status:503});const stripe=new Stripe(stripeKey);const sig=req.headers.get('stripe-signature');if(!sig)return NextResponse.json({error:'Missing signature'},{status:400});const raw=await req.text();let event:Stripe.Event;try{event=stripe.webhooks.constructEvent(raw,sig,secret)}catch{return NextResponse.json({error:'Invalid signature'},{status:400})}const s=adminClient();const existing=await s.from('payment_events').select('id').eq('provider_event_id',event.id).maybeSingle();if(existing.data)return NextResponse.json({received:true,duplicate:true});
if(event.type==='checkout.session.completed'){const session=event.data.object as Stripe.Checkout.Session;const userId=session.metadata?.user_id||null;const product=session.metadata?.product||null;await record(s,event,userId,product,session.amount_total,session.currency,session);if(userId&&product){if(product==='single')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'load_credit',quantity:1,source_reference:session.id});if(product==='pack10')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'load_pack',quantity:10,source_reference:session.id});if(product==='unlimited')await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'unlimited_posting',quantity:0,source_reference:String(session.subscription||session.id),ends_at:new Date(Date.now()+32*86400000).toISOString()});if(product.startsWith('ad_')&&session.metadata?.campaign_id){await s.from('advertising_campaigns').update({active:true,starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+30*86400000).toISOString()}).eq('id',session.metadata.campaign_id);await s.from('account_entitlements').insert({user_id:userId,entitlement_type:'ad_campaign',quantity:1,source_reference:session.id,ends_at:new Date(Date.now()+30*86400000).toISOString()})}}}
else if(event.type==='invoice.paid'){const invoice=event.data.object as Stripe.Invoice;const subscriptionId=typeof invoice.subscription==='string'?invoice.subscription:null;if(subscriptionId){const sub=await stripe.subscriptions.retrieve(subscriptionId);const userId=sub.metadata?.user_id;const product=sub.metadata?.product;if(userId&&product==='unlimited'){await s.from('account_entitlements').update({active:true,ends_at:new Date((sub.current_period_end+86400)*1000).toISOString()}).eq('user_id',userId).eq('entitlement_type','unlimited_posting').eq('source_reference',subscriptionId)}await record(s,event,userId||null,product||null,invoice.amount_paid,invoice.currency,invoice)}else await record(s,event,null,null,invoice.amount_paid,invoice.currency,invoice)}
else if(event.type==='customer.subscription.deleted'){const sub=event.data.object as Stripe.Subscription;const userId=sub.metadata?.user_id;if(userId)await s.from('account_entitlements').update({active:false,ends_at:new Date().toISOString()}).eq('user_id',userId).eq('entitlement_type','unlimited_posting');await record(s,event,userId||null,sub.metadata?.product||null,null,null,sub)}
else await record(s,event,null,null,null,null,event.data.object);
return NextResponse.json({received:true})}
