'use client';
import {useEffect,useMemo,useState} from 'react';
import {ensureProfile,getSupabaseBrowser,isSupabaseConfigured} from '../lib/supabase-browser';

const defaultProfile={name:'',homeCity:'',homeState:'',phone:'',email:'',cdlClass:'A',yearsExperience:'',endorsements:[],equipment:[],preferredWork:'OTR',preferredPay:'CPM',summary:''};
const defaultTruck={id:null,unit:'',year:'',make:'',model:'',vin:'',mileage:'',nextService:'',inspectionExpires:''};
const endorsementOptions=['Hazmat','Tanker','Doubles/Triples','Passenger','TWIC'];
const equipmentOptions=['Dry Van','Reefer','Flatbed','Tanker','Car Hauler','Hotshot','Oversize'];

export default function DriverHub(){
 const [profile,setProfile]=useState(defaultProfile),[truck,setTruck]=useState(defaultTruck),[docs,setDocs]=useState([{name:'CDL',expires:''},{name:'Medical Card',expires:''},{name:'TWIC',expires:''}]);
 const [saved,setSaved]=useState(false),[sync,setSync]=useState('Local beta mode'),[user,setUser]=useState(null),[profileId,setProfileId]=useState(null);
 useEffect(()=>{let mounted=true;async function boot(){try{const p=localStorage.getItem('dl-driver-passport'),t=localStorage.getItem('dl-my-truck'),d=localStorage.getItem('dl-docs');if(p)setProfile(JSON.parse(p));if(t)setTruck(JSON.parse(t));if(d)setDocs(JSON.parse(d));}catch{}
  const s=getSupabaseBrowser();if(!s)return;const {data}=await s.auth.getUser();if(data.user&&mounted){setUser(data.user);await loadCloud(data.user)}}boot();const s=getSupabaseBrowser();const listener=s?.auth.onAuthStateChange(async(_e,session)=>{if(session?.user){setUser(session.user);await loadCloud(session.user)}else{setUser(null);setProfileId(null);setSync('Local beta mode')}});return()=>{mounted=false;listener?.data.subscription.unsubscribe()};},[]);
 async function loadCloud(authUser){const s=getSupabaseBrowser();if(!s)return;setSync('Loading secure cloud data…');try{const owner=await ensureProfile(authUser);setProfileId(owner.id);
  const [{data:passport},{data:assets},{data:cloudDocs}]=await Promise.all([s.from('driver_passports').select('*').eq('profile_id',owner.id).maybeSingle(),s.from('equipment_assets').select('*').eq('owner_id',owner.id).eq('asset_type','truck').order('created_at').limit(1),s.from('driver_documents').select('*').eq('profile_id',owner.id).order('created_at')]);
  if(passport){const pref=passport.preferences||{};setProfile({name:owner.display_name||'',homeCity:pref.homeCity||'',homeState:owner.home_state||'',phone:pref.phone||'',email:authUser.email||'',cdlClass:passport.cdl_class||'A',yearsExperience:passport.years_experience??'',endorsements:passport.endorsements||[],equipment:passport.equipment_experience||[],preferredWork:pref.preferredWork||'OTR',preferredPay:pref.preferredPay||'CPM',summary:passport.professional_summary||''})}
  if(assets?.[0]){const a=assets[0],m=a.metadata||{};setTruck({id:a.id,unit:a.unit_number||'',year:a.year||'',make:a.make||'',model:a.model||'',vin:a.vin||'',mileage:a.mileage||'',nextService:m.nextService||'',inspectionExpires:m.inspectionExpires||''})}
  if(cloudDocs?.length)setDocs(cloudDocs.map(x=>({id:x.id,name:x.document_type,expires:x.expires_on||''})));setSync('Cloud sync active');}catch(e){setSync(`Cloud unavailable: ${e.message}`)}}
 const completion=useMemo(()=>{const fields=['name','homeCity','homeState','phone','email','yearsExperience','summary'];return Math.min(100,Math.round((fields.filter(k=>profile[k]).length/fields.length)*70+(profile.endorsements.length?15:0)+(profile.equipment.length?15:0)))},[profile]);
 function toggle(key,value){setProfile(p=>({...p,[key]:p[key].includes(value)?p[key].filter(x=>x!==value):[...p[key],value]}))}
 async function save(){localStorage.setItem('dl-driver-passport',JSON.stringify(profile));localStorage.setItem('dl-my-truck',JSON.stringify(truck));localStorage.setItem('dl-docs',JSON.stringify(docs));setSaved(true);setTimeout(()=>setSaved(false),1600);
  const s=getSupabaseBrowser();if(!s||!user){setSync('Saved on this device — sign in for cross-device sync');return}setSync('Syncing…');try{let pid=profileId;if(!pid){pid=(await ensureProfile(user)).id;setProfileId(pid)}
   await s.from('profiles').update({display_name:profile.name||'Driver',home_state:profile.homeState||null}).eq('id',pid);
   const {error:pErr}=await s.from('driver_passports').upsert({profile_id:pid,cdl_class:profile.cdlClass,years_experience:profile.yearsExperience?Number(profile.yearsExperience):null,endorsements:profile.endorsements,equipment_experience:profile.equipment,preferences:{homeCity:profile.homeCity,phone:profile.phone,preferredWork:profile.preferredWork,preferredPay:profile.preferredPay},professional_summary:profile.summary,updated_at:new Date().toISOString()});if(pErr)throw pErr;
   const asset={owner_id:pid,asset_type:'truck',unit_number:truck.unit||null,year:truck.year?Number(truck.year):null,make:truck.make||null,model:truck.model||null,vin:truck.vin||null,mileage:truck.mileage?Number(truck.mileage):null,metadata:{nextService:truck.nextService,inspectionExpires:truck.inspectionExpires}};
   let savedAsset;if(truck.id){const {data,error}=await s.from('equipment_assets').update(asset).eq('id',truck.id).select().single();if(error)throw error;savedAsset=data}else{const {data,error}=await s.from('equipment_assets').insert(asset).select().single();if(error)throw error;savedAsset=data;setTruck(t=>({...t,id:data.id}))}
   for(const d of docs){const row={profile_id:pid,document_type:d.name,expires_on:d.expires||null,sharing_scope:'private'};if(d.id){const {error}=await s.from('driver_documents').update(row).eq('id',d.id);if(error)throw error}else{const {data,error}=await s.from('driver_documents').insert(row).select().single();if(error)throw error;d.id=data.id}}
   setDocs([...docs]);setSync('Saved securely and synced across devices');
  }catch(e){setSync(`Saved locally; cloud sync failed: ${e.message}`)}}
 function updateDoc(i,key,value){setDocs(d=>d.map((x,n)=>n===i?{...x,[key]:value}:x))}
 return <div className="hub-layout">
  <aside className="hub-summary card"><p className="eyebrow">DRIVER PASSPORT</p><div className="passport-score"><b>{completion}%</b><span>profile complete</span></div><div className="progress"><span style={{width:`${completion}%`}}/></div><p>Build once, reuse for participating carrier applications, pilot-car work and your professional profile.</p><p className={`sync-note ${sync.includes('active')||sync.includes('securely')?'ok':'warn'}`}>{sync}</p><button onClick={save}>{saved?'Saved ✓':'Save Driver Passport'}</button></aside>
  <div className="hub-main">
   <section className="card"><div className="card-head"><div><p className="eyebrow">PROFESSIONAL PROFILE</p><h2>Driver Passport</h2></div><span className="badge">Private by default</span></div>
    <div className="form-grid"><label>Full name<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>Home city<input value={profile.homeCity} onChange={e=>setProfile({...profile,homeCity:e.target.value})}/></label><label>State<input maxLength="2" value={profile.homeState} onChange={e=>setProfile({...profile,homeState:e.target.value.toUpperCase()})}/></label><label>Phone<input value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><label>Email<input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label>Years commercial experience<input type="number" value={profile.yearsExperience} onChange={e=>setProfile({...profile,yearsExperience:e.target.value})}/></label><label>CDL class<select value={profile.cdlClass} onChange={e=>setProfile({...profile,cdlClass:e.target.value})}><option>A</option><option>B</option><option>C</option></select></label><label>Preferred work<select value={profile.preferredWork} onChange={e=>setProfile({...profile,preferredWork:e.target.value})}><option>OTR</option><option>Regional</option><option>Local</option><option>Dedicated</option><option>Owner-operator</option></select></label><label>Preferred pay<select value={profile.preferredPay} onChange={e=>setProfile({...profile,preferredPay:e.target.value})}><option>CPM</option><option>Hourly</option><option>Percentage</option><option>Salary</option><option>Per load</option></select></label></div>
    <h3>Endorsements & credentials</h3><div className="choice-row">{endorsementOptions.map(x=><button type="button" className={profile.endorsements.includes(x)?'choice active':'choice'} onClick={()=>toggle('endorsements',x)} key={x}>{x}</button>)}</div><h3>Equipment experience</h3><div className="choice-row">{equipmentOptions.map(x=><button type="button" className={profile.equipment.includes(x)?'choice active':'choice'} onClick={()=>toggle('equipment',x)} key={x}>{x}</button>)}</div><label>Professional summary<textarea rows="4" value={profile.summary} onChange={e=>setProfile({...profile,summary:e.target.value})}/></label>
   </section>
   <section className="card"><div className="card-head"><div><p className="eyebrow">MY GARAGE</p><h2>My Truck</h2></div><span className="badge">Cloud-ready</span></div><div className="form-grid"><label>Unit number<input value={truck.unit} onChange={e=>setTruck({...truck,unit:e.target.value})}/></label><label>Year<input value={truck.year} onChange={e=>setTruck({...truck,year:e.target.value})}/></label><label>Make<input value={truck.make} onChange={e=>setTruck({...truck,make:e.target.value})}/></label><label>Model<input value={truck.model} onChange={e=>setTruck({...truck,model:e.target.value})}/></label><label>VIN<input value={truck.vin} onChange={e=>setTruck({...truck,vin:e.target.value})}/></label><label>Mileage<input type="number" value={truck.mileage} onChange={e=>setTruck({...truck,mileage:e.target.value})}/></label><label>Next service<input type="date" value={truck.nextService} onChange={e=>setTruck({...truck,nextService:e.target.value})}/></label><label>Annual inspection expires<input type="date" value={truck.inspectionExpires} onChange={e=>setTruck({...truck,inspectionExpires:e.target.value})}/></label></div></section>
   <section className="card"><div className="card-head"><div><p className="eyebrow">DOCUMENT VAULT</p><h2>Expiration reminders</h2></div><button className="secondary" onClick={()=>setDocs([...docs,{name:'New document',expires:''}])}>Add document</button></div>{docs.map((d,i)=><div className="doc-row" key={d.id||i}><input value={d.name} onChange={e=>updateDoc(i,'name',e.target.value)}/><input type="date" value={d.expires} onChange={e=>updateDoc(i,'expires',e.target.value)}/><span>{d.expires?'Reminder enabled':'Add expiration'}</span></div>)}</section>
  </div>
 </div>
}
